PluginOutput::render():  Return correctly cut off output
Icinga/icingadb-web pull request #1026
Opened 2024-06-17 11:15 UTC by sukhwinder33445

fixes #1012

2024-06-18 15:23 UTC, tbauriedel commented
ref/NC/818175

2024-06-19 05:41 UTC, tbauriedel commented
There is already a PR to change the PluginOutput #1019

2024-06-19 07:44 UTC, sukhwinder33445 commented
As discussed offline, linked PR above is an extension and independent.

2024-07-22 14:35 UTC, nilmerg requested changes

2024-07-22 14:35 UTC, nilmerg commented on library/Icingadb/Util/PluginOutput.php
This still has numerous problems:

1. `PluginOutput::$enrichOutput` was previously a prerequisite for the replacement of state macros. Now it's ignored.
2. In case of plain text, `htmlspecialchars` was utilized. Now it's not.
3. Since replacement happens now before the check for HTML, once a macro is matched in plain text, it's now magically HTML and being purified for no reason. Or is 2) the reason? But then, why only if a macro has been replaced??

2024-07-22 14:35 UTC, nilmerg commented on test/php/library/Icingadb/Util/PluginOutputTest.php
monitoring also has a test, please migrate this over and see if it succeeds here afterwards

2024-07-24 08:03 UTC, nilmerg requested changes
Update phpstan's baseline completely please, not just partially.

2024-07-24 08:03 UTC, nilmerg commented on library/Icingadb/Util/PluginOutput.php
While you already added a return type to method `render`, you can now also add visibility to constants.

2024-07-24 14:08 UTC, nilmerg approved these changes

2024-07-24 14:09 UTC, merged