Show affected objects in the object detail for failed dependencies
Icinga/icingadb-web pull request #1072
Opened 2024-10-07 15:47 UTC by raviks789

resolves #1064

2024-10-23 13:02 UTC, sukhwinder33445 requested changes
The list is not limited to 5 items, as required.

2024-10-24 08:40 UTC, sukhwinder33445 commented on library/Icingadb/Widget/Detail/ObjectDetail.php
> +use ipl\Sql\Select;
This is unused.

2024-10-24 08:40 UTC, sukhwinder33445 commented on library/Icingadb/Widget/Detail/ObjectDetail.php
> +    protected function createAffectedObjects()
Please add the return type and PHPDoc.

2024-10-31 08:16 UTC, nilmerg requested changes

2024-10-31 08:16 UTC, nilmerg commented on library/Icingadb/Widget/Detail/ObjectDetail.php
> +                'redundancy_group.state.last_state_change'
Please combine this as well with the group's state.

2024-10-31 08:16 UTC, nilmerg commented on library/Icingadb/Widget/Detail/ObjectDetail.php
> +        $affectedObjects = DependencyNode::on($this->getDb())
This lists also objects which are not affected. The issue notes:

> Only direct children **and only those whose dependency has failed** are listed

2024-10-31 12:52 UTC, nilmerg approved these changes
LGTM!

2024-10-31 14:03 UTC, merged