ObjectSuggestions: Don't apply base filter to $customVars query
Icinga/icingadb-web pull request #1101
Opened 2024-11-26 15:19 UTC by sukhwinder33445

- The basefilter may contain relations, that are not know to `CustomvarFlat`, which can leads to errors. 
      For example: `RedundancygroupController:completeActions`'s base filter it not known to `CustomvarFlat`.

2025-01-20 10:02 UTC, nilmerg requested changes

2025-01-20 10:02 UTC, nilmerg commented on library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
> +        $this->applyRestrictions($customVars);
Please explain why this is required in such a global way. At the moment, this disables base filter appliance for all routes that have one and show a searchbar.

2025-01-20 10:02 UTC, nilmerg commented on library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
> +        $this->applyRestrictions($customVars);
e.g. hostgroup, servicegroup

2025-01-20 12:50 UTC, sukhwinder33445 commented on library/Icingadb/Web/Control/SearchBar/ObjectSuggestions.php
> +        $this->applyRestrictions($customVars);
As discussed offline, the base filter is not necessary here as it is already applied to the inner query (`$scalarQueries`) with `applyBaseFIlter()`.
Yes, the `applyBaseFIlter()` also applies restrictions to the inner query, but the `denylist/protect` can only be applied correctly if the `flatname` column is fetched.
Since the outer query retrieves the `flatname` column, the restriction must also be applied here (introduced with https://github.com/Icinga/icingadb-web/commit/5a808ae6d2063fba8fd667b214ad4550eb7f08fe).

2025-01-22 09:25 UTC, nilmerg approved these changes

2025-01-22 09:26 UTC, merged