Bugfix/right datatype gives an error
Icinga/icingadb-web pull request #122
Opened 2020-08-20 08:45 UTC by pmloei

For issue #119

2020-08-20 09:14 UTC, nilmerg requested changes
Left a comment. Also, please remove the commits from this branch that belong to the other issue.

2020-08-20 09:14 UTC, nilmerg commented on library/Icingadb/Compat/CompatObject.php
> +
That's unfortunately the wrong solution. Please register `action_url` as a legacy column instead.

2020-08-26 14:57 UTC, pmloei commented
> Left a comment. Also, please remove the commits from this branch that belong to the other issue.

Commits removed.

2020-09-07 11:07 UTC, nilmerg approved these changes

2020-09-07 11:07 UTC, merged