Add tool tip to ViewModeSwitcher.
Icinga/icingadb-web pull request #211
Opened 2021-06-14 10:32 UTC by raviks789

Tool tip to ViewModeSwitcher has been added here.

#144

2021-06-14 14:27 UTC, flourish86 requested changes

2021-06-14 14:27 UTC, flourish86 commented on library/Icingadb/Widget/ViewModeSwitcher.php
> +                $label->getAttributes()->add('title', sprintf('%s view active', $viewMode));
Please start tool tip sentence with Uppercase letter.

2021-06-16 10:17 UTC, nilmerg requested changes

2021-06-16 10:17 UTC, nilmerg commented on library/Icingadb/Widget/ViewModeSwitcher.php
> +                $label->getAttributes()->add('title', t(sprintf('%s view active', ucfirst($viewMode))));
Three issues regarding localisation:

a) gettext will parse the source code to extract messages, so translatable strings need to be directly wrapped by the translation function (i.e. `t('%s view active')`)
b) Passing a computed result to any translation function isn't possible. gettext extracts the arguments for such translation functions as `t()` and hence computed values won't be.. computed :smile: 
c) Translatable messages may of course contain placeholders for sprintf, but then it's usually a value that is localized differently (such as a date) or not localized at all (such as a number). This however is a name, and names are localizable, they're adjectives after all. So here we'd need three different messages, one for each mode.

2021-06-16 10:17 UTC, nilmerg commented on library/Icingadb/Widget/ViewModeSwitcher.php
> +                $label->getAttributes()->add('title', t(sprintf('Switch to %s view', $viewMode)));
See above.

2021-06-16 11:10 UTC, flourish86 approved these changes

2021-06-16 12:16 UTC, nilmerg commented on library/Icingadb/Widget/ViewModeSwitcher.php
> +                $label->getAttributes()->add('title', t(sprintf('%s view active', ucfirst($viewMode))));
This is resolved? You've only applied a) and b), what about c)?

2021-06-16 12:31 UTC, nilmerg approved these changes

2021-06-16 12:36 UTC, merged