Add 'Load More' button to NotificationController
Icinga/icingadb-web pull request #239
Opened 2021-08-18 13:25 UTC by sukhwinder33445

2021-08-19 09:14 UTC, nilmerg requested changes
Since this is mostly the same code as for the history overview, I'd like to see a trait being used for this functionality:

* Create a new trait `Icinga\Module\Icingadb\Common\LoadMore`
* Put the new properties of `NotificationList` and methods into this trait (except `init`)
* Use the trait inside `NotificationList` and `HistoryList`
* Expect a `ResultSet` in method `getIterator` as param (that's essentially `realData`)
* Introduce a new method `setLoadMoreUrl` into the trait
  * Use that method in the controller when creating the `NotificationList` and pass it the url with the before param
* Don't add the `ShowMore` widget in the controller, but let `getIterator` add it once the actual data is exhausted. With the url, page size and page number it should be possible to do that.

2021-08-20 09:32 UTC, nilmerg requested changes
Nice! :+1: Just a few small changes left :)

2021-08-20 09:32 UTC, nilmerg commented on library/Icingadb/Common/LoadMore.php
> +     * Set the page number
That's not a page number.

2021-08-20 09:32 UTC, nilmerg commented on library/Icingadb/Common/LoadMore.php
> +    protected function getIterator($result)
* Add phpdoc
* Require that `$result` is a `ResultSet`
  * Then override `__construct` in `HistoryList` and `NotificationList` to also require there that `$data` is a `ResultSet` (but then just call the parent constructor, it's just about the type declaration)

2021-08-20 10:53 UTC, nilmerg requested changes

2021-08-20 10:53 UTC, nilmerg commented on library/Icingadb/Common/LoadMore.php
> +     * Set the url for LoadMore widget
`LoadMore` doesn't exist as widget, at least I read this as if there's a `Icingadb\Widget\LoadMore`. Just describe what the url is used for: to fetch *more* items

2021-08-20 10:53 UTC, nilmerg commented on library/Icingadb/Common/LoadMore.php
> +    protected function getIterator($result)
Also add the type declaration for the parameter in the method interface.

2021-08-20 10:53 UTC, nilmerg commented on library/Icingadb/Common/LoadMore.php
> +     * Add the page separator and the "LoadMore" button at the desired position
That's the description of what it additionally does (if it begins with *Adds*), not the main functionality. Keep that with *Adds* as extended description and add a main description what the method returns. And on that note, also add a `@returns Generator` annotation.

2021-08-20 13:34 UTC, nilmerg requested changes
Please check all other usages of `HistoryList` and `NotificationList`. It's not just the EventController which is affected.

2021-08-20 13:47 UTC, sukhwinder33445 commented
I have already checked. NotificationList is not used anywhere else and HistoryList already gets a Resultset parameter (used in the HostController, ServiceController and in the EventController (fixed)).

2021-08-20 13:49 UTC, nilmerg commented
Aye, but it's not just the constructor you've changed :wink:

2021-08-20 14:19 UTC, sukhwinder33445 commented
Yes, I also changed the getIterator method in the LoadMore trait, but it has no effect. Am I missing something?

2021-08-20 14:25 UTC, nilmerg commented
Just an example: https://github.com/Icinga/icingadb-web/blob/feature/add-loadmore-to-notificationsController/application/controllers/HostController.php#L163-L164

2021-08-20 14:38 UTC, sukhwinder33445 commented
Oh, I see. It is no longer necessary to use ShowMore in the controller. I will change it soon.

2021-08-23 10:53 UTC, nilmerg approved these changes

2021-08-23 12:13 UTC, merged