UserDetail: Enhance user detail view
Icinga/icingadb-web pull request #309
Opened 2021-08-30 15:55 UTC by sukhwinder33445

fix #281 #279

2021-09-01 10:41 UTC, nilmerg requested changes
We should enrich the states and types somehow. How about using a `TagList` for both, a localized label and then link to a filtered notification list with the state/type and user filter applied?

2021-09-02 12:21 UTC, nilmerg requested changes
Sorry I have to step back from my suggestion to use a TagList. The filters for the notification list resulting from this are waaaaaay too expensive. We cannot provide such expensive filters by default.

So, please make states and types simple comma separated text again. Also:

* Make them localizable. I'd want to see `Problem`, not `problem`. (And don't dare to use `ucfirst` for this :wink: )
* Show a dash again for no value everywhere. That's how we do it everywhere else and it's sufficient

2021-09-03 07:09 UTC, sukhwinder33445 commented
> waaaaaay too expensive

You mean in terms of performance? Can you please explain why? it's just doing the same thing as we filter something with two options.

2021-09-03 08:47 UTC, nilmerg commented
I have 3.5 million notifications in my history. If I use such a filter, I'll sit there waiting for 4+ minutes to get any result. This is acceptable if the filter is my own. But a link in the UI shouldn't lead to this.

2021-09-03 11:52 UTC, sukhwinder33445 commented
I see, thank you for the explanation.

2021-09-07 10:39 UTC, nilmerg requested changes

2021-09-07 10:39 UTC, nilmerg commented on library/Icingadb/Widget/Detail/UserDetail.php
> +                    $localizedTypes[] = t('DowntimeStart');
It's a label/title, so please use general word boundaries/structure. (i.e. spaces)

2021-09-07 13:03 UTC, nilmerg submitted a review, later dismissed

2021-09-07 13:05 UTC, sukhwinder33445 commented
I am working on separating the states for host and services.

2021-09-07 13:07 UTC, nilmerg commented
Yep, also don't forget [this](https://github.com/Icinga/icingadb-web/issues/279#issuecomment-905575411). We should remove the mail and pager from list items. The "list" being a "table" isn't good either: #192

2021-09-08 12:03 UTC, nilmerg requested changes
* There is no UNKNOWN state for hosts
* You forgot the OK state in `localizeStates`
* `separateStates` cannot get the result of `localizeStates` as input

2021-09-10 12:19 UTC, merged