Add `Host-/Servicegroup` grid views
Icinga/icingadb-web pull request #355
Opened 2021-09-15 16:16 UTC by Yonas-net

resolves #221

2023-06-07 11:30 UTC, nilmerg requested changes

2023-06-14 09:01 UTC, nilmerg requested changes

2023-06-14 09:01 UTC, nilmerg commented on public/css/widget/group-grid.less
> +            text-overflow: ellipsis;
There's a mixin for this

2023-06-14 09:01 UTC, nilmerg commented on public/css/widget/group-grid.less
I'd like to discuss the change requests here in person, so please notify me before working on them.

2023-06-20 08:10 UTC, nilmerg requested changes

2023-06-20 08:10 UTC, nilmerg commented on library/Icingadb/Widget/ItemTable/ServicegroupGridCell.php
Please use the `Translation` trait in here, instead of `t` and `tp`.

2023-06-20 09:07 UTC, raviks789 commented on library/Icingadb/Web/Control/ViewModeSwitcher.php
> +    protected function protectId($id)
True

2023-06-20 09:08 UTC, raviks789 commented on public/css/widget/table-layout.less
> +  }
I guess this was incorrectly introduced. This has been removed now.

2023-06-20 10:14 UTC, nilmerg requested changes
The table layout is broken now

2023-06-20 12:06 UTC, nilmerg approved these changes

2023-06-20 12:06 UTC, merged