Redesign migrate popup
Icinga/icingadb-web pull request #408
Opened 2021-10-27 13:18 UTC by sukhwinder33445

resolves #407

2021-11-03 09:29 UTC, nilmerg requested changes

2021-11-03 09:29 UTC, nilmerg commented on public/css/widget/migrate-popup.less
> +  font-size: .875em;
Why is that on the entire popup? This way it has an effect not only on font-size, but on the entire layout of the popup. I thought it's only the text that's too big.

Currently I have difficulty too read the "Don't show this again" label. It's way too small.

2021-11-03 14:38 UTC, nilmerg commented
@flourish86 Please take a look now.

2021-11-03 16:40 UTC, flourish86 approved these changes
Looks fine now. Thanks!

2021-11-04 07:53 UTC, nilmerg approved these changes

2021-11-04 07:53 UTC, merged