GitHub Actions: Add PHPStan
Icinga/icingadb-web pull request #423
Opened 2021-11-06 09:38 UTC by lippserd

2023-08-17 15:07 UTC, yhabteab commented on library/Icingadb/Widget/Detail/PerfDataTable.php
> +            if (! empty($col)) {
**Before:**
<img width="620" alt="Bildschirmfoto 2023-08-17 um 17 07 18" src="https://github.com/Icinga/icingadb-web/assets/57616252/fdb77cbd-33cd-42dc-89ca-9994bacd056e">


With your changes:
<img width="620" alt="Bildschirmfoto 2023-08-17 um 17 06 49" src="https://github.com/Icinga/icingadb-web/assets/57616252/720c4ebb-21dc-4307-a6cb-6a5fd84b9307">

2023-09-01 13:28 UTC, nilmerg requested changes

2023-09-01 13:28 UTC, nilmerg commented on library/Icingadb/Data/CsvResultSet.php
>      public function current()
:array ?

2023-09-01 13:28 UTC, nilmerg commented on library/Icingadb/Data/JsonResultSet.php
>      public function current()
: array ?

2023-09-01 13:28 UTC, nilmerg commented on library/Icingadb/Hook/ActionsHook/ObjectActionsHook.php
> +                /** @var HostActionsHook $hookName */
phpstorm gets this right. This previously meant $hook for a reason, as that's what's used by the loop below.

2023-09-01 13:28 UTC, nilmerg commented on library/Icingadb/Hook/ExtensionHook/ObjectDetailExtensionHook.php
> +                /** @var HostDetailExtensionHook $hookName */
same here

2023-09-01 13:28 UTC, nilmerg commented on library/Icingadb/Hook/ExtensionHook/ObjectsDetailExtensionHook.php
> -                /** @var HostsDetailExtensionHook $hook */
same here

2023-09-01 13:28 UTC, nilmerg commented on library/Icingadb/Web/Controller.php
> +            ->setTitle($this->view->title ?? '')
is this really required?

2023-09-01 13:28 UTC, nilmerg commented on library/Icingadb/Widget/Detail/PerfDataTable.php
> +                        [ 'class' => 'sparkline-col']
please remove the leading space before 'class

2023-09-05 08:04 UTC, nilmerg requested changes
please rebase and fix the conflict

2023-09-05 12:55 UTC, nilmerg approved these changes

2023-09-05 12:56 UTC, merged