Fix too extensive host notification recipients
Icinga/icingadb-web pull request #442
Opened 2021-11-11 14:20 UTC by lippserd

Previously, host notification recipients also included notification recipients from their services.

2021-11-11 14:22 UTC, nilmerg submitted a review, later dismissed

2021-11-11 14:44 UTC, lippserd commented
Don't merge yet. Still testing whether this works.

2021-11-11 14:45 UTC, nilmerg commented
Then make it a draft next time please :wink:

2021-11-11 14:45 UTC, lippserd commented
> Then make it a draft next time please 😉

Sry!

2021-11-12 08:51 UTC, julianbrost commented
Fixes the issue for me. An intermediate patch showed too little results sometimes, but I don't remember the exact conditions when this happened, so I tried a few different user/group configuration and everything showed up fine with this patch.

2021-11-12 14:41 UTC, nilmerg requested changes

2021-11-12 14:41 UTC, nilmerg commented on library/Icingadb/Widget/Detail/ObjectDetail.php
> +            }
Empty lines after control structures, please.

2021-11-12 15:18 UTC, nilmerg approved these changes

2021-11-12 15:34 UTC, merged