ApiTransportForm: Don't use text to create password elements
Icinga/icingadb-web pull request #460
Opened 2021-11-22 09:22 UTC by yhabteab

resolves #459

2021-11-22 09:24 UTC, yhabteab commented
Blocked By

- https://github.com/Icinga/ipl-html/pull/57

2021-11-22 13:38 UTC, yhabteab commented
@cla-bot check

2021-12-08 12:23 UTC, nilmerg requested changes

2021-12-08 12:23 UTC, nilmerg commented on application/forms/ApiTransportForm.php
>              'label'         => t('API Password')
We should probably add `autocomplete=new-password` here. (https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password)

2021-12-08 14:14 UTC, nilmerg approved these changes

2021-12-09 07:44 UTC, merged