Redis: Apply volatile state results directly to the state model
Icinga/icingadb-web pull request #566
Opened 2022-06-27 14:40 UTC by yhabteab

Since all the inconsistent column/redis key names have been renamed, we don't have to cache redis keys
separately anymore. This PR applies all the `Service/Host` volatile state results directly to the
respective state model.

2022-06-28 08:26 UTC, nilmerg approved these changes

2022-06-29 07:50 UTC, lippserd requested changes
Icinga 2 may not write keys to redis if there is no value. Something like the following is required in DB Web:

```
$data = array_merge(array_fill_keys($columns, null), $data);
```

2022-06-29 08:33 UTC, nilmerg requested changes
Please remove class `VolatileState` entirely, it's unused (and obsolete) now.

2022-06-29 08:42 UTC, nilmerg requested changes

2022-06-29 08:42 UTC, nilmerg commented on library/Icingadb/Redis/VolatileStateResults.php
> +                $data = array_merge(array_fill_keys($keys, null), $data);
You're overriding the decoded json data here, leading to a fully unset state.

2022-06-29 09:02 UTC, nilmerg requested changes

2022-06-29 09:02 UTC, nilmerg commented on library/Icingadb/Redis/VolatileStateResults.php
> +                $data = array_intersect_key($data, $keys);
Where did the array_flip went? Now $data is empty and the redis result is not used??

2022-06-29 10:37 UTC, nilmerg approved these changes

2022-06-29 10:38 UTC, merged