Provide generic tts integration
Icinga/icingadb-web pull request #630
Opened 2022-08-29 10:08 UTC by raviks789

ref #629

2022-09-01 06:25 UTC, nilmerg commented
Planned for v1.1. Once working on this version, I'd like to discuss whether it makes sense to re-use some existing hooks or whether to introduce entirely new hooks. (e.g. `CommentDetailExtensionHook`) Why? Because I'd like to get rid of `TicketHook` in Icinga Web 2 and have its implementation provided by generictts. (What the missing support for it in Icinga DB Web showed, is that it's the only module making use of the hook, so why the hell not..)

2022-09-02 08:20 UTC, lippserd commented
A new hook like `CommentDetailExtensionHook` sounds good to me as well!

2022-10-05 09:19 UTC, nilmerg requested changes

2022-10-05 09:19 UTC, nilmerg commented on library/Icingadb/Common/TicketLinks.php
> +/* Icinga DB Web | (c) 2021 Icinga GmbH | GPLv2 */
It's 2022 ;)

2022-10-05 09:19 UTC, nilmerg commented on library/Icingadb/Common/TicketLinks.php
> +        $tickets = Icinga::app()->getViewRenderer()->view->tickets;
I don't quite see an advantage in this. Just retrieve the hook here directly by calling `Hook::first()`.

2022-10-05 09:19 UTC, nilmerg commented on library/Icingadb/Common/TicketLinks.php
> +            return isset($tickets) ? $tickets->createLinks($text) : $text;
Why not move the `isset()` into the `if`?

2022-10-05 09:19 UTC, nilmerg commented on library/Icingadb/Web/Controller.php
> +        }
Please remove this.

2022-10-05 09:51 UTC, nilmerg requested changes

2022-10-05 09:51 UTC, nilmerg commented on library/Icingadb/Web/Controller.php
> +use Icinga\Application\Hook;
There's still this now unused use statement

2022-10-11 11:41 UTC, nilmerg approved these changes
Thanks!

2022-10-13 08:59 UTC, merged