Fix/SetApiTimeout
Icinga/icingadb-web pull request #649
Opened 2022-09-19 13:12 UTC by pdolinic

Trying to connect to the API, there is no default timeout specified. This one sets a debatable one with 15 seconds, whereas monitoring has 30s.

2022-10-05 06:32 UTC, nilmerg requested changes

2022-10-05 06:32 UTC, nilmerg commented on library/Icingadb/Command/Transport/ApiCommandTransport.php
> +            $response = (new Client(['timeout' => '15']))
Please pass the seconds as integer, not as string.

2022-10-11 11:53 UTC, nilmerg commented
Please add the missing space as mentioned in the checks and take a look at your emails associated with the commits. I'd like to include this in the next minor update.

2022-10-11 16:12 UTC, lippserd submitted a review, later dismissed

2022-10-11 16:12 UTC, lippserd commented on library/Icingadb/Command/Transport/ApiCommandTransport.php
> +            $response = (new Client(['timeout' => 15 ]))
Remove the space after the `15` please. Only the one before is required.

2022-10-12 07:25 UTC, nilmerg approved these changes

2022-10-13 09:00 UTC, merged