SlaReport: Breakdown into an hour view showing only downtimes
Icinga/icingadb-web pull request #651
Opened 2022-09-30 10:49 UTC by jhoxhaa

2023-01-18 09:24 UTC, yhabteab requested changes

2023-01-18 09:24 UTC, yhabteab commented on library/Icingadb/ProvidedHook/Reporting/SlaReport.php
> +            } elseif ($config['breakdown'] != 'hour') {
Think about how you can handle these `if ... elseif` branches in just a single `if` block.

2023-01-19 11:04 UTC, yhabteab commented on library/Icingadb/ProvidedHook/Reporting/SlaReport.php
> +                    $format = 'h:i:s A';
Why not just use `H:i:s` as a format or is there some technical context to this that I don't get?

2023-01-19 13:34 UTC, yhabteab approved these changes

2023-01-30 15:08 UTC, lippserd reviewed
What does "showing only downtimes" mean here?

2023-01-30 16:11 UTC, davixd commented
@lippserd 
I'm the requester of https://github.com/Icinga/icingaweb2-module-reporting/issues/146. As far as I could follow: jhoxhaa implemented my feature request on point. "showing only downtimes" should mean the following:  as the breakdown range now gets more detailed (in this case a hour view is choosable for each day), in this case its not necessary to create a report for each day with a breakdown of a hour which shows only the availability of 100% in a detailed view of a hour range. Such report would have several unnecessary pages.  My idea was to create a breakdown in a hour view, only when a downtime occurred.

Example Report for January 2023:
...
29. January - 92%
14:00 - 16:00 8% (Downtime occurrence)
30. January - 100%
...

instead of:
...
29. January - 100%
00:00 0%
01:00 0%
02:00 0%
03:00 0%
04:00 0%
and so on (24 hours)
30. January - 100%
...

As the day summary shows 100% of availability, I do not need to have a breakdown into hours. As the day shows 92% availability, our management would like to know in which hours of the day the downtime did occurred, so there is a breakdown of hours necessary (but only the affected hours). I hope it makes sense. For us this feature is really necessary to be able to use this kind of Reports for our management.

2023-06-15 06:45 UTC, merged