Add reporting hooks to DetailsAction
Icinga/icingadb-web pull request #655
Opened 2022-10-12 15:17 UTC by jhoxhaa

fixes #704

2023-01-18 10:16 UTC, yhabteab reviewed
I think here is not the appropriate repository for these hooks. Also, those hooks shouldn't be object extensions, but rather `HostActions` and `ServiceActions` and have to be provided by the reporting module.

cc @nilmerg

2023-01-18 10:40 UTC, nilmerg commented
No, that's the correct location. Icinga DB Web provides the sla report functionality for reporting. Reporting has no idea what SLA means and can't provide actions for this kind of report.

But you're correct with the assumption that these should be actions. Though, I'd even question whether this should be a hook at all. `ObjectDetail::createActions` could do this instead.

2023-01-31 07:41 UTC, lippserd commented
> Though, I'd even question whether this should be a hook at all.

The reports are also hooks. I think it makes sense to keep the non-core module functionality separated.

2023-05-30 13:02 UTC, nilmerg requested changes
Please let the hooks extend `Icinga\Module\Icingadb\Hook\HostActionsHook` and `Icinga\Module\Icingadb\Hook\ServiceActionsHook`.

2023-05-31 08:55 UTC, nilmerg requested changes

2023-05-31 08:55 UTC, nilmerg commented on library/Icingadb/ProvidedHook/CreateServiceSlaReport.php
> +        $wrapper = Html::tag('div');
Please don't use a wrapper element. The other content also doesn't use one. Use a `HtmlDocument` as wrapper instead.

2023-05-31 08:55 UTC, nilmerg commented on library/Icingadb/ProvidedHook/CreateHostSlaReport.php
> +        $wrapper = Html::tag('div');
Please don't use a wrapper element. The other content also doesn't use one. Use a `HtmlDocument` as wrapper instead.

2023-05-31 08:55 UTC, nilmerg commented on library/Icingadb/ProvidedHook/CreateServiceSlaReport.php
> +            ->add(Html::tag('a', ['href' => $url], 'Create Service SLA Report'));
Please use the `ipl\Web\Widget\Link` class and translate both labels with `ipl\I18n\Translation::translate()`

2023-05-31 08:55 UTC, nilmerg commented on library/Icingadb/ProvidedHook/CreateHostSlaReport.php
> +            ->add(Html::tag('a', ['href' => $url], 'Create Host SLA Report'));
Please use the `ipl\Web\Widget\Link` class and translate both labels with `ipl\I18n\Translation::translate()`

2023-05-31 08:55 UTC, nilmerg commented on run.php
> +    $this::exists('reporting') && Icinga::app()->getModuleManager()->hasEnabled('reporting')
`exists` already checks the enabled state if I'm not mistaken :thinking:

2023-05-31 08:55 UTC, nilmerg commented on run.php
> +    && Auth::getInstance()->hasPermission('reporting/reports')
Accessing the authentication at this stage (run.php runs very early) may cause issues, especially on routes that normally don't need authentication. Placing this here causes everything to require authentication as run.php runs always. Please check the permission in the hooks itself.

2023-05-31 13:07 UTC, nilmerg requested changes
Please put always an empty line after closing a control structure.

e.g.:
```
    }

    return $result;
```

Otherwise it looks fine now.

2023-05-31 13:36 UTC, nilmerg approved these changes

2023-05-31 13:38 UTC, merged