SlaReport: Add checkbox to export total % of hosts/services for CSV a…
Icinga/icingadb-web pull request #678
Opened 2022-11-17 16:04 UTC by jhoxhaa

…nd JSON

2023-03-15 16:37 UTC, lippserd requested changes

2023-03-15 16:37 UTC, lippserd commented on library/Icingadb/ProvidedHook/Reporting/SlaReport.php
> +        $form->addElement('checkbox', 'csv-json-export', [
For field names we always use `snake_case`. I would also suggest to rename the field to `export_total`.

2023-03-15 16:37 UTC, lippserd commented on library/Icingadb/ProvidedHook/Reporting/SlaReport.php
> +            'label'          => 'Export total for CSV and JSON',
`Export total values to CSV and JSON`

2023-03-15 16:37 UTC, lippserd commented on library/Icingadb/ProvidedHook/Reporting/SlaReport.php
> +            'checkedValue'   => '1',
Can you add a comment with a little explanation why we're setting `0` and `1` here?

2023-03-23 14:47 UTC, lippserd requested changes

2023-03-23 14:47 UTC, lippserd commented on library/Icingadb/ProvidedHook/Reporting/SlaReport.php
> +            'label'          => 'Export total for CSV and JSON',
Translate missing :).

2023-07-10 10:30 UTC, yhabteab commented
@lippserd please review & merge this PR.

2023-07-10 10:37 UTC, lippserd approved these changes

2023-07-10 10:37 UTC, merged