Improve performance of Icinga 2 API commands processed in bulk
Icinga/icingadb-web pull request #721
Opened 2023-03-01 15:28 UTC by Al2Klimov

Let me explain how I came here in the first place.

While discussing removal of some deprecated features with @Thomas-Gelf he opted against removing the command pipe. He considered it faster than the Icinga 2 API for massive stuff submission. I thought: wait, we have one system which eventually does massive stuff submission via API – Icinga Web. I even actually did that while testing Icinga ack sync. And it was indeed slow. I asked myself: what could it already do by itself to do this faster? What does it do right now? While reverse-engineering this repo I came to the conclusion that it renders, sends and awaits commands one by one. I remembered that @yhabteab did somewhere something with PHP event loops and let him show me them. They could help me sending multiple commands concurrently. It turned out more complicated than I thought, but then I remembered something else. @julianbrost digged out than our API supports not only DSL filters and filter_vars which iterate over all objects. It also supports targeting a specific object by name. This repo already does this. But it supports targeting multiple specific objects by array of names as well. That's what I did here.

* Icinga/icinga2#6307
* Icinga/icinga2#9652
* Icinga/icinga2#9188

Now the command forms render at best exactly one Icinga 2 API action request targeting all selected objects at once, not one request per object. Commenting e.g. 500 hosts now takes 4s, not 40. For this now commands and forms always handle multiple objects by design. PHP generators everywhere don't permit the RAM to blow up. Delete*Command are now parts of the ObjectsCommand family.

## TODO

* [x] Approval of the concept in general
* [x] Agreement on the implementation details
* [x] What's up with GHA? (@Al2Klimov)
* [x] Tests of all code usages of all commands DB-Web supports

2023-03-01 15:31 UTC, Al2Klimov commented on application/forms/Command/Object/ScheduleCheckForm.php
> +        ));
... **and** a whiteboard for this. 😅

![8F58897B-41A5-4D25-8BE4-E8A6FFB17186](https://user-images.githubusercontent.com/6053266/222185988-01b20bf0-e4b1-48b5-a558-cd75cc583ff3.jpeg)

2023-07-11 10:48 UTC, nilmerg requested changes

2023-07-11 12:10 UTC, Al2Klimov commented on library/Icingadb/Command/Object/ObjectsCommand.php
> +     * @param   Model[] $objects
I'm afraid the declaration is pretty limited on this:

https://stackoverflow.com/a/34273821

2023-07-11 12:25 UTC, nilmerg commented on library/Icingadb/Command/Object/ObjectsCommand.php
> +     * @param   Model[] $objects
I know. But you shouldn't deviate from the declared argument type in the docstring. That's not just me who's not liking it, https://github.com/Icinga/icingadb-web/pull/423 won't as well.

2023-07-11 13:07 UTC, Al2Klimov commented on library/Icingadb/Command/Object/ObjectsCommand.php
> +     * @param   Model[] $objects
I.e. I shall only advertise an array (of T) if I declare an (even untyped) `array`?

2023-07-11 13:22 UTC, nilmerg commented on library/Icingadb/Command/Object/ObjectsCommand.php
> +     * @param   Model[] $objects
Yes, either remove the declaration or document the type as `Traversable`

2023-07-11 14:58 UTC, Al2Klimov commented on library/Icingadb/Command/Object/ObjectsCommand.php
> +     * @param   Model[] $objects
I think there's a misunderstanding. I meant neither, but to document `T[]`, but to PHP-declare `array` as PHP can't `T[]` (only PHP**Doc**):

> I'm afraid the declaration is pretty limited on this:
> 
> https://stackoverflow.com/a/34273821

OK?

2023-07-12 08:21 UTC, nilmerg commented on library/Icingadb/Command/Object/ObjectsCommand.php
> +     * @param   Model[] $objects
You didn't want an array in the first place. So why not:

```
/**
* @param Model[] $objects
*/
public function setObjects($objects)
```

or

```
/**
* @param Traversable $objects
*/
public function setObjects(Traversable $objects)
```

2023-07-13 14:47 UTC, Al2Klimov commented on library/Icingadb/Command/Object/ObjectsCommand.php
> +     * @param   Model[] $objects
> You didn't want an array in the first place.

I changed my mind, especially after https://github.com/Icinga/icingadb-web/pull/721#discussion_r1259558630 . Arrays are harder to screw up, so I chose to PHP-enforce `array`. OK?

2023-07-17 07:53 UTC, nilmerg commented on library/Icingadb/Command/Object/ObjectsCommand.php
> +     * @param   Model[] $objects
If you enforce `array`, you prevent the usage of database queries and require everyone passing the result of a `$query->fetchAll()` blowing up the memory usage. That's not OK.

2023-07-25 11:49 UTC, Al2Klimov commented on application/forms/Command/CommandForm.php
> +    }
So far I think I've fixed everything ex. this. Are you sure we wouldn't violate any interface rules like 1) rewind 2) valid ... here?

2023-07-25 13:50 UTC, Al2Klimov commented on application/forms/Command/CommandForm.php
> +    }
```
php > function g() { yield 1; yield 2; }
php > $x=g();
php > var_dump($x->valid());
bool(true)
php > var_dump($x->rewind());
NULL
php > var_dump($x->valid());
bool(true)
php > var_dump($x->current());
int(1)
php >
```

OK... :D

2023-07-25 14:18 UTC, Al2Klimov commented on application/forms/Command/CommandForm.php
> +    }
Oh, almost forgot:


```
php > function g() { if (0) yield 1; }
php > $x=g();
php > var_dump($x->valid());
bool(false)
php >
```

For the record.

2023-07-25 14:48 UTC, nilmerg commented on application/forms/Command/CommandForm.php
> +    }
Then don't use it:

```php
$objects = function ($it) {
    foreach ($it as $o) {
        if (...) {
            yield $o;
        }
    }
}();

```

2023-07-28 07:45 UTC, nilmerg requested changes

2023-07-28 07:45 UTC, nilmerg commented on application/forms/Command/Object/CheckNowForm.php
> +use Traversable;
Cleanup unused usages.

2023-07-28 07:45 UTC, nilmerg commented on application/forms/Command/Object/DeleteCommentForm.php
> +use Traversable;
Cleanup unused usages.

2023-07-28 07:45 UTC, nilmerg commented on application/forms/Command/Object/DeleteDowntimeForm.php
> +use Traversable;
Cleanup unused usages.

2023-07-28 07:45 UTC, nilmerg commented on application/forms/Command/Object/ProcessCheckResultForm.php
> +use CallbackFilterIterator;
Cleanup unused usages.

2023-07-28 07:45 UTC, nilmerg commented on application/forms/Command/Object/ScheduleCheckForm.php
> +use Traversable;
Cleanup unused usages.

2023-08-02 11:20 UTC, Al2Klimov commented
# Tests

## To do list

```
$ git diff --stat master..bulk-cmd application/forms/Command
 application/forms/Command/CommandForm.php                         | 51 +++++++++++++++++++++++++++++++--------------------
 application/forms/Command/Instance/ToggleInstanceFeaturesForm.php |  7 ++-----
 application/forms/Command/Object/AcknowledgeProblemForm.php       | 42 ++++++++++++++++++------------------------
 application/forms/Command/Object/AddCommentForm.php               | 34 ++++++++++++++--------------------
 application/forms/Command/Object/CheckNowForm.php                 | 45 +++++++++++++++++++++++----------------------
 application/forms/Command/Object/DeleteCommentForm.php            | 30 ++++++++++++++++--------------
 application/forms/Command/Object/DeleteDowntimeForm.php           | 36 +++++++++++++++++++-----------------
 application/forms/Command/Object/ProcessCheckResultForm.php       | 37 ++++++++++++++++++-------------------
 application/forms/Command/Object/RemoveAcknowledgementForm.php    | 24 +++++++++---------------
 application/forms/Command/Object/ScheduleCheckForm.php            | 45 +++++++++++++++++++++++----------------------
 application/forms/Command/Object/ScheduleHostDowntimeForm.php     | 53 +++++++++++++++++++++++++----------------------------
 application/forms/Command/Object/ScheduleServiceDowntimeForm.php  | 44 +++++++++++++++++++-------------------------
 application/forms/Command/Object/SendCustomNotificationForm.php   | 28 +++++++++++-----------------
 application/forms/Command/Object/ToggleObjectFeaturesForm.php     | 32 +++++++++++++++-----------------
 14 files changed, 243 insertions(+), 265 deletions(-)
$
```

## Instance/ToggleInstanceFeaturesForm.php

![Bildschirmaufnahme 2023-08-02 um 12 46 39](https://github.com/Icinga/icingadb-web/assets/6053266/5fb88e2a-b91a-465d-a746-8a6df6137e75)

## Object/AcknowledgeProblemForm.php

![Bildschirmaufnahme 2023-08-02 um 12 57 32](https://github.com/Icinga/icingadb-web/assets/6053266/53ac3b73-8624-42fe-b214-14f069f328fb)

## Object/AddCommentForm.php

![Bildschirmaufnahme 2023-08-02 um 12 59 25](https://github.com/Icinga/icingadb-web/assets/6053266/0add2756-8a5e-4faa-a43b-f80279cc0fa1)

## Object/CheckNowForm.php

![Bildschirmaufnahme 2023-08-02 um 13 01 16](https://github.com/Icinga/icingadb-web/assets/6053266/c1a248e7-b79b-4885-bc9b-77c2afb3bb9f)

## Object/DeleteCommentForm.php

![Bildschirmaufnahme 2023-08-02 um 13 03 06](https://github.com/Icinga/icingadb-web/assets/6053266/ef155664-e70f-4019-90dc-bdd64c5aaf86)

## Object/ScheduleServiceDowntimeForm.php

![Bildschirmaufnahme 2023-08-02 um 13 04 02](https://github.com/Icinga/icingadb-web/assets/6053266/54c8cc44-adda-4ec9-8d63-5b7180d5ac2a)

## Object/DeleteDowntimeForm.php

![Bildschirmaufnahme 2023-08-02 um 13 05 00](https://github.com/Icinga/icingadb-web/assets/6053266/f21b4c33-1d0e-414d-b9a2-6aaf1fe731fe)

## Object/RemoveAcknowledgementForm.php

![Bildschirmaufnahme 2023-08-02 um 13 06 22](https://github.com/Icinga/icingadb-web/assets/6053266/6d30fee6-2c50-4a13-927d-5a6d967db19f)

## Object/ProcessCheckResultForm.php

![Bildschirmaufnahme 2023-08-02 um 13 07 04](https://github.com/Icinga/icingadb-web/assets/6053266/c978c16e-db4b-4cec-baa0-6eca1bccc6d8)

## Object/ToggleObjectFeaturesForm.php

![Bildschirmaufnahme 2023-08-02 um 13 07 23](https://github.com/Icinga/icingadb-web/assets/6053266/a7c59559-0432-4c9f-9f2d-1e379a3039e8)

## Object/ScheduleCheckForm.php

![Bildschirmaufnahme 2023-08-02 um 13 09 18](https://github.com/Icinga/icingadb-web/assets/6053266/a2857ea4-da81-462f-b52f-f41855547d57)

## Object/SendCustomNotificationForm.php

![Bildschirmaufnahme 2023-08-02 um 13 10 54](https://github.com/Icinga/icingadb-web/assets/6053266/9b077813-d726-4860-9cc4-9543b47a2655)

## Conclusion

It still works.

2023-08-10 07:32 UTC, nilmerg approved these changes

2023-08-10 07:33 UTC, merged