ObjectAuthorization: Quote rolename containing `dot (.)` correctly
Icinga/icingadb-web pull request #750
Opened 2023-05-19 08:29 UTC by sukhwinder33445

fixes #742

2023-05-19 08:44 UTC, nilmerg requested changes

2023-05-19 08:44 UTC, nilmerg commented on library/Icingadb/Authentication/ObjectAuthorization.php
> +            $roleName = $this->getDb()->quoteIdentifier((array) $role->getName());
Please don't cast it. You never know when PHP decides to transform `'abc'` to `['a', 'b', 'c']` in some future version. (We don't want *the name to be an array*, but *inside an array*)

2023-05-19 08:56 UTC, nilmerg reviewed
Did you verify that the checks still work? (Not that just the error is fixed but the checks still fail)

2023-05-19 09:27 UTC, sukhwinder33445 commented
The applied restrictions work.

2023-05-22 08:42 UTC, nilmerg requested changes
There's still another issue:

* Choose multiple hosts which are available by a restriction from a role with dots in its name
* Try to set a downtime (or perform any other quick action)

2023-05-23 13:43 UTC, nilmerg requested changes

2023-05-24 07:50 UTC, sukhwinder33445 commented on library/Icingadb/Authentication/ObjectAuthorization.php
> +                    $alias = trim($alias, '"');
Since we pass the `$roleName` to `quoteIdentifier()`, it is always quoted. I have now removed the quotes before adding it to the array.

2023-05-30 11:56 UTC, nilmerg approved these changes

2023-05-30 11:56 UTC, merged