Add `CopyToClipboard` button to copy executed command in `Source` tab
Icinga/icingadb-web pull request #758
Opened 2023-05-25 08:44 UTC by raviks789

resolves #677

2023-05-30 08:38 UTC, nilmerg commented on public/css/widget/object-inspection.less
To me, this is a bit too much CSS. I think we can place most of this in ipl-web, by using some assumptions:

It's either a child: `[data-clipboard-source] > .copy-to-clipboard`
Or a direct sibling: `[data-clipboard-source] + .copy-to-clipboard`

Of course, the JS needs to attach the data attribute if it's not there, but that shouldn't be an issue.

2023-06-14 07:29 UTC, nilmerg requested changes
Please move the behavior to Icinga Web again. Sorry for the back and forth.

2023-06-14 07:29 UTC, nilmerg commented on library/Icingadb/Widget/Detail/EventDetail.php
> +                $commandOutput =  new PluginOutputContainer(
Please remove the added space

2023-06-14 07:29 UTC, nilmerg commented on library/Icingadb/Common/ObjectInspectionDetail.php
> +                                $value->addAttributes(['id' => $name])
eh, where does this come from???

2023-06-15 07:49 UTC, nilmerg approved these changes

2023-06-20 10:04 UTC, merged

2023-06-24 21:25 UTC, gbin2265 commented
Hello, 

All the service and host pages have the error after upgrading to the latest snapshot  icingadb-web-1.0.2+82.g67fc7f5-1687561409.el7.noarch.rpm | 2023-06-24 01:50

Uncaught Error: Class 'ipl\Web\Widget\CopyToClipboard' not found in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ObjectDetail.php:422

I can't find the CopyToClipboard file anywhere.

regards,
Geert

2023-06-25 11:01 UTC, gbin2265 commented
Hello, 

I found the problem!
The latest version was not installed from the icinga-php-library because the repo order is not correct.

Here's the list of commands:
yum list --showduplicates icinga-php-library


icinga-php-library.noarch                                         0.12.0-1.el7                                                             rhel.packages.icinga
icinga-php-library.noarch                                         0.12.0+3.g2ae9c91-1687554236.el7                                         rhel.packages.icinga.snapshot
icinga-php-library.noarch                                         0.12.0+3.g9c77d12-1686344659.el7                                         rhel.packages.icinga.snapshot
icinga-php-library.noarch                                         0.12.0+3.g50a5d94-1686949414.el7                                         rhel.packages.icinga.snapshot
icinga-php-library.noarch                                         0.12.0+3.g855d297-1684530225.el7                                         rhel.packages.icinga.snapshot
icinga-php-library.noarch                                         0.12.0+3.gc7e3bf3-1685739855.el7                                         rhel.packages.icinga.snapshot
icinga-php-library.noarch                                         0.12.0+3.gdf60104-1685135016.el7                                         rhel.packages.icinga.snapshot


The latest version for yum is version 0.12.0+3.gdf60104-1685135016.el7 and not version 0.12.0+3.g2ae9c91-1687554236.el7 dated 24Jun2023
If you sort , as yum does, gdf60104 is later in version as g2ae9c91.