Use ipl web widgets
Icinga/icingadb-web pull request #830
Opened 2023-08-09 12:33 UTC by yhabteab

## Blocked by
- https://github.com/Icinga/ipl-web/pull/183

2023-08-25 12:37 UTC, sukhwinder33445 requested changes
Please commit new changes in a new commit.

2023-08-25 12:37 UTC, sukhwinder33445 commented on public/css/mixins.less
>  }
Why is this not moved as well? It has nothing icingadb-web specific.

2023-08-28 12:38 UTC, sukhwinder33445 requested changes

2023-08-28 12:38 UTC, sukhwinder33445 commented on library/Icingadb/Widget/ItemList/StateListItem.php
> +        return null;
```suggestion
$since = null;
if (..) {
    $since = $val;
} elseif (..) {
    $since = $val;
}

return $since;
```

2023-09-08 13:09 UTC, nilmerg submitted a review, later dismissed

2023-09-08 13:47 UTC, nilmerg approved these changes

2023-09-08 14:23 UTC, sukhwinder33445 approved these changes

2023-09-08 14:23 UTC, merged