Add document for the configuration of the IcingaDB-Modul
Icinga/icingadb-web pull request #971
Opened 2024-02-13 06:36 UTC by RincewindsHat

This adds a listing of the possible settings for the module in the configuration files.
It is quite similar to the monitoring module, but wasn't documented for this one.

2024-02-13 08:06 UTC, nilmerg commented
Please also add a section to `10-Migration.md` regarding this topic

2024-02-13 12:20 UTC, RincewindsHat commented
@nilmerg better?

2024-03-14 15:03 UTC, nilmerg requested changes
Please also rebase, to fix the actions

2024-03-15 13:01 UTC, RincewindsHat commented on doc/10-Migration.md
> +## General configuration via config.ini
This is intentionally placed here, it describes how one would migrate that kind of configuration from the monitoring module to the icingadb module

2024-03-15 13:10 UTC, RincewindsHat commented on doc/10-Migration.md
> +migrating those options is done by simple copying the configuration file to the icingadb module.
fixed

2024-03-15 13:13 UTC, RincewindsHat commented on doc/10-Migration.md
> +The behaviour of those options remains the same.
fixed?

2024-03-15 15:27 UTC, nilmerg commented on doc/10-Migration.md
> +## General configuration via config.ini
The entire document is about that. The document however has different sections:

* Configuration (General, global stuff)
* Navigation (user specific customization)
* Dashboards (user specific customization)
* Views and Exports (Custom views)
* Access Control

Your addition clearly belongs to the first section. If you'd keep it where it is, the reader would be surprised to find this after reading through the entire document.

2024-03-15 15:29 UTC, nilmerg commented on doc/10-Migration.md
> +The behaviour of those options remains the same.
Oh come on. This is **not** about command transports :roll_eyes:

2024-03-17 21:34 UTC, RincewindsHat commented on doc/10-Migration.md
> +The behaviour of those options remains the same.
my oversight. sorry.

2024-03-17 21:35 UTC, RincewindsHat commented on doc/10-Migration.md
> +## General configuration via config.ini
ah yes, my fault. I did misinterpret the structure.

2024-03-18 08:12 UTC, nilmerg requested changes

2024-03-18 08:12 UTC, nilmerg commented on doc/03-Configuration.md
> +Some default values for actions with dialogs in the UI can be adjusted (e.g. While acknowledging a problem).
Was something wrong with my suggestion?

You're now talking of *some values* and in the next sentence of *these options*. I'd wonder, which options are meant.

And while there are indeed *actions **without** dialogs*, I don't think this nuance needs to be mentioned here.

Though, I see why you added *some* at the start, as I used *particular* to refer to dialogs myself.

So what about:

```suggestion
You can adjust some default values of options users have while interacting with particular dialogs in the UI. (e.g. While acknowledging a problem)
```

2024-03-18 08:57 UTC, nilmerg approved these changes
Thanks ;)

2024-03-18 08:58 UTC, merged